# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

# environment/computational parameters
device: cuda
num_workers: 4

# dataset parameters
data_root: /data
num_classes: 5

# training hyperparameters
image_size: [128, 128]
num_epochs: 200
batch_size: 32
learning_rate: 0.001
weight_decay: 0.001